const JIRA_TOKEN = {
    SUCCESS_LOAD: 'SUCCESS - LOAD_JIRA_TOKEN',
    FAILED_LOAD: 'FAILED - LOAD_JIRA_TOKEN',
    SUCCESS_SAVE: 'SUCCESS - JIRA TOKEN SAVED',
    FAILED_SAVE: 'FAILED - JIRA TOKEN NOT SAVED',
    SUCCESS_UPDATE: 'SUCCESS - JIRA TOKEN UPDATED',
    FAILED_UPDATE: 'FAILED - JIRA TOKEN NOT UPDATED',
    SUCCESS_VERIFY: 'SUCCESS - JIRA TOKEN VERIFIED',
    FAILED_VERIFY: 'FAILED - JIRA TOKEN NOT VERIFIED',
};

const JIRA_TICKETS = {
    INITIALISE_FETCH: 'IN PROGRESS - FETCH_JIRA_TICKETS',
    SUCCESS_FETCH: 'SUCCESS - FETCH_JIRA_TICKETS',
    FAILED_FETCH: 'FAILED - FETCH_JIRA_TICKETS',
    REMOVE_TICKET: 'REMOVE_TICKET',

    INITIALISE_SAVE: 'IN PROGRESS - JIRA TICKETS SAVE IN DATABASE',
    SUCCESS_SAVE: 'SUCCESS - JIRA TICKETS SAVED IN DATABASE',
    FAILED_SAVE: 'FAILED - JIRA TICKETS NOT SAVED IN DATABASE',

    INITIALISE_LOAD: 'INITIALISE - LOAD_BACKEND_TICKETS',
    SUCCESS_LOAD: 'SUCCESS - LOAD_BACKEND_TICKETS',
    FAILED_LOAD: 'FAILED - LOAD_BACKEND_TICKETS',

    INITIALISE_SAVED_FETCH: 'IN PROGRESS - FETCH_SAVED_JIRA_TICKETS',
    SUCCESS_SAVED_FETCH: 'SUCCESS - FETCH_SAVED_JIRA_TICKETS',
    FAILED_SAVED_FETCH: 'FAILED - FETCH_SAVED_JIRA_TICKETS',

    INITIALISE_DELETE: 'INITIALISE - DELETE_TICKET_AT_BACKEND',
    SUCCESS_DELETE: 'SUCCESS - DELETE_TICKET_AT_BACKEND',
    FAILED_DELETE: 'FAILED - DELETE__TICKET_AT_BACKEND',
}

export { JIRA_TOKEN, JIRA_TICKETS };
