const POKER_INVITES_ACTION = {
    START: 'START_LOAD_POKER_INVITES',
    SUCCESS: 'SUCCESS_LOAD_POKER_INVITES',
    FAILED: 'FAILED_LOAD_POKER_INVITES',
    ACCEPT: 'ACCEPT_POKER_INVITE',
    DECLINE: 'DECLINE_POKER_INVITE',
    CANCEL: 'CANCEL_POKER_INVITE',
};

export { POKER_INVITES_ACTION };
